# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

# This file has been modified by Kathy Grimes and is no longer directly based off of 'project1.ui'

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(14)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(50, 55, 150, 30))
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_password = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_password.setGeometry(QtCore.QRect(205, 50, 111, 40))
        self.pushButton_password.setFont(font)
        self.pushButton_password.setObjectName("pushButton_password")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(10, 20, 331, 20))
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")

        
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update.setGeometry(QtCore.QRect(10, 20, 250, 25))
        self.pushButton_update.setObjectName("pushbutton_update")
        self.pushButton_update.setFont(font)
        self.pushButton_update.setVisible(0)
        self.label_currenttemp = QtWidgets.QLabel(self.centralwidget)
        self.label_currenttemp.setGeometry(QtCore.QRect(30, 50, 250, 17))
        self.label_currenttemp.setObjectName("label_currenttemp")
        self.label_currenttemp.setFont(font)
        self.label_currenttemp.setVisible(0)
        self.label_currenthum = QtWidgets.QLabel(self.centralwidget)
        self.label_currenthum.setGeometry(QtCore.QRect(30, 100, 250, 17))
        self.label_currenthum.setObjectName("label_currenthum")
        self.label_currenthum.setFont(font)
        self.label_currenthum.setVisible(0)
        self.label_lowesttemp = QtWidgets.QLabel(self.centralwidget)
        self.label_lowesttemp.setGeometry(QtCore.QRect(500, 50, 250, 17))
        self.label_lowesttemp.setObjectName("label_lowesttemp")
        self.label_lowesttemp.setFont(font)
        self.label_lowesttemp.setVisible(0)
        self.label_lowesthum = QtWidgets.QLabel(self.centralwidget)
        self.label_lowesthum.setGeometry(QtCore.QRect(500, 100, 250, 17))
        self.label_lowesthum.setObjectName("label_lowesthum")
        self.label_lowesthum.setFont(font)
        self.label_lowesthum.setVisible(0)
        self.label_highesttemp = QtWidgets.QLabel(self.centralwidget)
        self.label_highesttemp.setGeometry(QtCore.QRect(500, 200, 250, 17))
        self.label_highesttemp.setObjectName("label_highesttemp")
        self.label_highesttemp.setFont(font)
        self.label_highesttemp.setVisible(0)
        self.label_highesthum = QtWidgets.QLabel(self.centralwidget)
        self.label_highesthum.setGeometry(QtCore.QRect(500, 250, 250, 17))
        self.label_highesthum.setObjectName("label_highesthum")
        self.label_highesthum.setFont(font)
        self.label_highesthum.setVisible(0)
        self.label_averagetemp = QtWidgets.QLabel(self.centralwidget)
        self.label_averagetemp.setGeometry(QtCore.QRect(30, 200, 250, 17))
        self.label_averagetemp.setObjectName("label_averagetemp")
        self.label_averagetemp.setFont(font)
        self.label_averagetemp.setVisible(0)
        self.label_averagehum = QtWidgets.QLabel(self.centralwidget)
        self.label_averagehum.setGeometry(QtCore.QRect(30, 250, 250, 17))
        self.label_averagehum.setObjectName("label_averagehum")
        self.label_averagehum.setFont(font)
        self.label_averagehum.setVisible(0)
        self.lineEdit_currenttempvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_currenttempvalue.setGeometry(QtCore.QRect(300, 50, 104, 31))
        self.lineEdit_currenttempvalue.setObjectName("lineEdit_tempvalue")
        self.lineEdit_currenttempvalue.setFont(font)
        self.lineEdit_currenttempvalue.setVisible(0)
        self.lineEdit_currenthumvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_currenthumvalue.setGeometry(QtCore.QRect(300, 100, 104, 31))
        self.lineEdit_currenthumvalue.setObjectName("lineEdit_humvalue")
        self.lineEdit_currenthumvalue.setFont(font)
        self.lineEdit_currenthumvalue.setVisible(0)
        self.lineEdit_lowesttempvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lowesttempvalue.setGeometry(QtCore.QRect(770, 50, 104, 31))
        self.lineEdit_lowesttempvalue.setObjectName("lineEdit_tempvalue")
        self.lineEdit_lowesttempvalue.setFont(font)
        self.lineEdit_lowesttempvalue.setVisible(0)
        self.lineEdit_lowesthumvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lowesthumvalue.setGeometry(QtCore.QRect(770, 100, 104, 31))
        self.lineEdit_lowesthumvalue.setObjectName("lineEdit_humvalue")
        self.lineEdit_lowesthumvalue.setFont(font)
        self.lineEdit_lowesthumvalue.setVisible(0)
        self.lineEdit_highesttempvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_highesttempvalue.setGeometry(QtCore.QRect(770, 200, 104, 31))
        self.lineEdit_highesttempvalue.setObjectName("lineEdit_tempvalue")
        self.lineEdit_highesttempvalue.setFont(font)
        self.lineEdit_highesttempvalue.setVisible(0)
        self.lineEdit_highesthumvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_highesthumvalue.setGeometry(QtCore.QRect(770, 250, 104, 31))
        self.lineEdit_highesthumvalue.setObjectName("lineEdit_humvalue")
        self.lineEdit_highesthumvalue.setFont(font)
        self.lineEdit_highesthumvalue.setVisible(0)
        self.lineEdit_averagetempvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_averagetempvalue.setGeometry(QtCore.QRect(300, 200, 104, 31))
        self.lineEdit_averagetempvalue.setObjectName("lineEdit_tempvalue")
        self.lineEdit_averagetempvalue.setFont(font)
        self.lineEdit_averagetempvalue.setVisible(0)
        self.lineEdit_averagehumvalue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_averagehumvalue.setGeometry(QtCore.QRect(300, 250, 104, 31))
        self.lineEdit_averagehumvalue.setObjectName("lineEdit_humvalue")
        self.lineEdit_averagehumvalue.setFont(font)
        self.lineEdit_averagehumvalue.setVisible(0)

        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.label_nocon = QtWidgets.QLabel(self.centralwidget)
        self.label_nocon.setGeometry(QtCore.QRect(10, 100, 300, 100))
        self.label_nocon.setFont(font)
        self.label_nocon.setObjectName("label_nocon")
        self.label_nocon.setVisible(0)
        
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(10)
        self.label_currentupdatetime = QtWidgets.QLabel(self.centralwidget)
        self.label_currentupdatetime.setGeometry(QtCore.QRect(10, 310, 450, 20))
        self.label_currentupdatetime.setFont(font)
        self.label_currentupdatetime.setObjectName("label_currentupdatetime")
        self.label_currentupdatetime.setVisible(0)
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(8)
        self.label_templowestupdatetime = QtWidgets.QLabel(self.centralwidget)
        self.label_templowestupdatetime.setGeometry(QtCore.QRect(510, 80, 380, 20))
        self.label_templowestupdatetime.setFont(font)
        self.label_templowestupdatetime.setObjectName("label_templowestupdatetime")
        self.label_templowestupdatetime.setVisible(0)
        self.label_temphighestupdatetime = QtWidgets.QLabel(self.centralwidget)
        self.label_temphighestupdatetime.setGeometry(QtCore.QRect(510, 130, 380, 20))
        self.label_temphighestupdatetime.setFont(font)
        self.label_temphighestupdatetime.setObjectName("label_temphighestupdatetime")
        self.label_temphighestupdatetime.setVisible(0)
        self.label_humlowestupdatetime = QtWidgets.QLabel(self.centralwidget)
        self.label_humlowestupdatetime.setGeometry(QtCore.QRect(510, 230, 380, 20))
        self.label_humlowestupdatetime.setFont(font)
        self.label_humlowestupdatetime.setObjectName("label_humlowestupdatetime")
        self.label_humlowestupdatetime.setVisible(0)
        self.label_humhighestupdatetime = QtWidgets.QLabel(self.centralwidget)
        self.label_humhighestupdatetime.setGeometry(QtCore.QRect(510, 280, 380, 20))
        self.label_humhighestupdatetime.setFont(font)
        self.label_humhighestupdatetime.setObjectName("label_humhighestupdatetime")
        self.label_humhighestupdatetime.setVisible(0)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 2"))
        self.pushButton_password.setText(_translate("MainWindow", "Enter"))
        self.label_password.setText(_translate("MainWindow", "Please enter the password:"))
        self.pushButton_update.setText(_translate("MainWindow", "Switch Temperature Units"))
        self.label_currenttemp.setText(_translate("MainWindow", "Current Temperature (*F):  "))
        self.label_currenthum.setText(_translate("MainWindow", "Current Humidity (%):  "))
        self.label_lowesttemp.setText(_translate("MainWindow", "Lowest Temperature (*F):  "))
        self.label_lowesthum.setText(_translate("MainWindow", "Lowest Humidity (%):  "))
        self.label_highesttemp.setText(_translate("MainWindow", "Highest Temperature (*F):  "))
        self.label_highesthum.setText(_translate("MainWindow", "Highest Humidity (%):  "))
        self.label_averagetemp.setText(_translate("MainWindow", "Average Temperature (*F):  "))
        self.label_averagehum.setText(_translate("MainWindow", "Average Humidity (%):  "))
        self.label_nocon.setText(_translate("MainWindow", "Sensor NOT connected"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())
